---
abstract: 'A sub-class of the standard TT view which'
author:
  - 'Tomas Doran C<< <bobtfish@bobtfish.net> >>'
build_requires:
  Catalyst::Action::RenderView: 0
  Test::More: 0
  Test::WWW::Mechanize::Catalyst: 0
distribution_type: module
generated_by: 'Module::Install version 0.77'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Catalyst-View-TT-XHTML
no_index:
  directory:
    - inc
    - t
requires:
  Catalyst::Runtime: 0
  Catalyst::View::TT: 0
  HTTP::Negotiate: 0
  MRO::Compat: 0
resources:
  license: http://dev.perl.org/licenses/
  repository: http://dev.catalyst.perl.org/repos/Catalyst/Catalyst-View-TT-XHTML
version: 1.003
